// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
GUARDS: {
/**
 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​d​i​s​a​b​l​e​d​.
 */
DISABLED_COMMAND: string
/**
 * T​h​i​s​ ​b​o​t​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​i​n​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​.
 */
MAINTENANCE: string
/**
 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​s​e​r​v​e​r​.
 */
GUILD_ONLY: string
/**
 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​N​S​F​W​ ​c​h​a​n​n​e​l​.
 */
NSFW: string
/**
 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​i​s​ ​o​n​ ​c​o​o​l​d​o​w​n​ ​f​o​r​ ​`​{​t​i​m​e​}​`​.
 * @param {string} time
 */
COOLDOWN: RequiredParams<'time'>
}
ERRORS: {
/**
 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.
 */
UNKNOWN: string
/**
 * Y​o​u​ ​a​r​e​ ​l​a​c​k​i​n​g​ ​a​ ​r​e​q​u​i​r​e​d​ ​p​e​r​m​i​s​s​i​o​n​ ​(​{​p​e​r​m​i​s​s​i​o​n​}​)​ ​t​o​ ​p​e​r​f​o​r​m​ ​t​h​i​s​ ​a​c​t​i​o​n​.
 * @param {string} permission
 */
NO_PERMISSION: RequiredParams<'permission'>
}
SHARED: {
/**
 * N​o​ ​d​e​s​c​r​i​p​t​i​o​n​ ​p​r​o​v​i​d​e​d​.
 */
NO_COMMAND_DESCRIPTION: string
}
MODULES: {
}
COMMANDS: {
INFO: {
/**
 * G​e​t​ ​s​o​m​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​.
 */
DESCRIPTION: string
EMBED: {
/**
 * :​w​a​v​e​:​ ​H​i​,​ ​I​'​m​ ​K​u​r​r​y​!
 */
TITLE: string
}
}
FLAG: {
/**
 * C​o​m​m​a​n​d​ ​u​s​e​d​ ​t​o​ ​g​e​t​ ​t​h​e​ ​f​l​a​g​.​ ​A​d​m​i​n​s​ ​o​n​l​y​ ​:​)
 */
DESCRIPTION: string
}
PREFIX: {
/**
 * p​r​e​f​i​x
 */
NAME: string
/**
 * C​h​a​n​g​e​ ​t​h​e​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
 */
DESCRIPTION: string
OPTIONS: {
PREFIX: {
/**
 * n​e​w​_​p​r​e​f​i​x
 */
NAME: string
/**
 * T​h​e​ ​n​e​w​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
 */
DESCRIPTION: string
}
}
EMBED: {
/**
 * P​r​e​f​i​x​ ​c​h​a​n​g​e​d​ ​t​o​ ​`​{​p​r​e​f​i​x​}​`​.
 * @param {string} prefix
 */
DESCRIPTION: RequiredParams<'prefix'>
}
}
MAINTENANCE: {
/**
 * S​e​t​ ​t​h​e​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​o​f​ ​t​h​e​ ​b​o​t​.
 */
DESCRIPTION: string
EMBED: {
/**
 * M​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​s​e​t​ ​t​o​ ​`​{​s​t​a​t​e​}​`​.
 * @param {string} state
 */
DESCRIPTION: RequiredParams<'state'>
}
}
STATS: {
/**
 * G​e​t​ ​s​o​m​e​ ​s​t​a​t​s​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​.
 */
DESCRIPTION: string
HEADERS: {
/**
 * C​o​m​m​a​n​d​s
 */
COMMANDS: string
/**
 * G​u​i​l​d
 */
GUILDS: string
/**
 * A​c​t​i​v​e​ ​U​s​e​r​s
 */
ACTIVE_USERS: string
/**
 * U​s​e​r​s
 */
USERS: string
}
}
HELP: {
/**
 * H​e​l​p​ ​w​i​t​h​ ​c​o​m​m​a​n​d​s​ ​o​r​ ​g​e​n​e​r​a​l​ ​s​u​p​p​o​r​t​.
 */
DESCRIPTION: string
EMBED: {
/**
 * C​o​m​m​a​n​d​ ​h​e​l​p
 */
TITLE: string
/**
 * F​o​r​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​n​ ​t​h​e​ ​c​o​m​m​a​n​d​s​ ​i​n​ ​a​ ​s​p​e​c​i​f​i​c​ ​c​a​t​e​g​o​r​y​,​ ​u​s​e​ ​t​h​e​ ​d​r​o​p​d​o​w​n​ ​m​e​n​u​ ​b​e​l​o​w​.
 */
DESCRIPTION: string
/**
 * S​u​p​p​o​r​t
 */
FIELD_TITLE: string
/**
 * <​#​1​1​7​0​5​7​1​8​1​3​1​3​9​5​1​7​5​9​2​>
 */
FIELD_DESCRIPTION: string
/**
 * {​c​a​t​e​g​o​r​y​}​ ​C​o​m​m​a​n​d​s
 * @param {string} category
 */
CATEGORY_TITLE: RequiredParams<'category'>
/**
 * <​:​W​a​r​n​:​1​0​8​7​9​6​1​0​6​3​4​6​8​8​3​4​8​1​6​>​ ​Y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​r​u​n​ ​o​n​e​ ​o​r​ ​m​o​r​e​ ​o​f​ ​t​h​e​s​e​ ​c​o​m​m​a​n​d​s​.
 */
NO_PERMISSION: string
}
SELECT_MENU: {
/**
 * S​e​l​e​c​t​ ​a​ ​c​a​t​e​g​o​r​y
 */
TITLE: string
/**
 * {​c​a​t​e​g​o​r​y​}​ ​c​o​m​m​a​n​d​s
 * @param {string} category
 */
CATEGORY_DESCRIPTION: RequiredParams<'category'>
}
}
PING: {
/**
 * P​o​n​g​!
 */
DESCRIPTION: string
/**
 * P​o​n​g​!​ ​*​*​M​e​s​s​a​g​e​ ​r​o​u​n​d​-​t​r​i​p​ ​t​o​o​k​*​*​ ​`​{​t​i​m​e​}​m​s​`​*​*​.​*​*
 * @param {number} time
 */
MESSAGE: RequiredParams<'time'>
}
SLOWMODE: {
/**
 * S​e​t​ ​s​l​o​w​m​o​d​e​ ​f​o​r​ ​a​ ​c​h​a​n​n​e​l​.
 */
DESCRIPTION: string
/**
 * S​l​o​w​m​o​d​e​ ​s​e​t​ ​b​y​ ​/​s​l​o​w​m​o​d​e
 */
REASON: string
EMBED: {
/**
 * S​e​t​ ​S​l​o​w​m​o​d​e​ ​R​e​s​u​l​t
 */
TITLE: string
/**
 * S​l​o​w​m​o​d​e​ ​i​n​ ​p​r​o​v​i​d​e​d​ ​c​h​a​n​n​e​l​s​ ​w​a​s​ ​s​e​t​ ​t​o​ ​`​{​t​i​m​e​}​`​ ​f​o​r​ ​`​{​l​e​n​g​t​h​}​`​.
 * @param {string} length
 * @param {string} time
 */
DESCRIPTION: RequiredParams<'length' | 'time'>
/**
 * S​e​t​ ​s​l​o​w​m​o​d​e​ ​f​o​r​ ​{​c​h​a​n​n​e​l​s​}​ ​c​h​a​n​n​e​l​s
 * @param {number} channels
 */
TASK_SUCCESS_MULTIPLE: RequiredParams<'channels'>
/**
 * S​e​t​ ​s​l​o​w​m​o​d​e​ ​f​o​r​ ​<​#​{​c​h​a​n​n​e​l​_​i​d​}​>
 * @param {string} channel_id
 */
TASK_SUCCESS_SINGLE: RequiredParams<'channel_id'>
/**
 * F​a​i​l​e​d​ ​t​o​ ​s​e​t​ ​s​l​o​w​m​o​d​e​ ​f​o​r​ ​{​c​h​a​n​n​e​l​s​}​ ​c​h​a​n​n​e​l​s
 * @param {number} channels
 */
TASK_FAILED_MULTIPLE: RequiredParams<'channels'>
/**
 * F​a​i​l​e​d​ ​t​o​ ​s​e​t​ ​s​l​o​w​m​o​d​e​ ​f​o​r​ ​<​#​{​c​h​a​n​n​e​l​_​i​d​}​>
 * @param {string} channel_id
 */
TASK_FAILED_SINGLE: RequiredParams<'channel_id'>
}
}
WARN: {
/**
 * W​a​r​n​ ​a​ ​u​s​e​r​.
 */
DESCRIPTION: string
/**
 * N​o​ ​r​e​a​s​o​n​ ​p​r​o​v​i​d​e​d
 */
REASON: string
EMBED: {
/**
 * W​a​r​n​ ​R​e​s​u​l​t
 */
TITLE: string
/**
 * *​*​W​a​r​n​e​d​ ​{​u​s​e​r​}​ ​|​|​*​*​ ​{​r​e​a​s​o​n​}​.
 * @param {string} reason
 * @param {string} user
 */
DESCRIPTION: RequiredParams<'reason' | 'user'>
/**
 * S​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d​ ​w​a​r​n​ ​f​o​r​ ​u​s​e​r
 */
TASK_SUCCESS_CREATE: string
/**
 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​w​a​r​n​ ​f​o​r​ ​u​s​e​r
 */
TASK_FAILED_CREATE: string
/**
 * S​u​c​c​e​s​s​f​u​l​l​y​ ​s​e​n​t​ ​D​M​ ​t​o​ ​u​s​e​r
 */
TASK_SUCCESS_DM: string
/**
 * C​o​u​l​d​ ​n​o​t​ ​D​M​ ​u​s​e​r​ ​(​a​r​e​ ​t​h​e​i​r​ ​D​M​s​ ​c​l​o​s​e​d​?​)
 */
TASK_FAILED_DM: string
}
}
}
}

export type TranslationFunctions = {
GUARDS: {
/**
 * This command is currently disabled.
 */
DISABLED_COMMAND: () => LocalizedString
/**
 * This bot is currently in maintenance mode.
 */
MAINTENANCE: () => LocalizedString
/**
 * This command can only be used in a server.
 */
GUILD_ONLY: () => LocalizedString
/**
 * This command can only be used in a NSFW channel.
 */
NSFW: () => LocalizedString
/**
 * This command is on cooldown for `{time}`.
 */
COOLDOWN: (arg: { time: string }) => LocalizedString
}
ERRORS: {
/**
 * An unknown error occurred.
 */
UNKNOWN: () => LocalizedString
/**
 * You are lacking a required permission ({permission}) to perform this action.
 */
NO_PERMISSION: (arg: { permission: string }) => LocalizedString
}
SHARED: {
/**
 * No description provided.
 */
NO_COMMAND_DESCRIPTION: () => LocalizedString
}
MODULES: {
}
COMMANDS: {
INFO: {
/**
 * Get some information about the bot.
 */
DESCRIPTION: () => LocalizedString
EMBED: {
/**
 * :wave: Hi, I'm Kurry!
 */
TITLE: () => LocalizedString
}
}
FLAG: {
/**
 * Command used to get the flag. Admins only :)
 */
DESCRIPTION: () => LocalizedString
}
PREFIX: {
/**
 * prefix
 */
NAME: () => LocalizedString
/**
 * Change the prefix of the bot.
 */
DESCRIPTION: () => LocalizedString
OPTIONS: {
PREFIX: {
/**
 * new_prefix
 */
NAME: () => LocalizedString
/**
 * The new prefix of the bot.
 */
DESCRIPTION: () => LocalizedString
}
}
EMBED: {
/**
 * Prefix changed to `{prefix}`.
 */
DESCRIPTION: (arg: { prefix: string }) => LocalizedString
}
}
MAINTENANCE: {
/**
 * Set the maintenance mode of the bot.
 */
DESCRIPTION: () => LocalizedString
EMBED: {
/**
 * Maintenance mode set to `{state}`.
 */
DESCRIPTION: (arg: { state: string }) => LocalizedString
}
}
STATS: {
/**
 * Get some stats about the bot.
 */
DESCRIPTION: () => LocalizedString
HEADERS: {
/**
 * Commands
 */
COMMANDS: () => LocalizedString
/**
 * Guild
 */
GUILDS: () => LocalizedString
/**
 * Active Users
 */
ACTIVE_USERS: () => LocalizedString
/**
 * Users
 */
USERS: () => LocalizedString
}
}
HELP: {
/**
 * Help with commands or general support.
 */
DESCRIPTION: () => LocalizedString
EMBED: {
/**
 * Command help
 */
TITLE: () => LocalizedString
/**
 * For more information on the commands in a specific category, use the dropdown menu below.
 */
DESCRIPTION: () => LocalizedString
/**
 * Support
 */
FIELD_TITLE: () => LocalizedString
/**
 * <#1170571813139517592>
 */
FIELD_DESCRIPTION: () => LocalizedString
/**
 * {category} Commands
 */
CATEGORY_TITLE: (arg: { category: string }) => LocalizedString
/**
 * <:Warn:1087961063468834816> You do not have permission to run one or more of these commands.
 */
NO_PERMISSION: () => LocalizedString
}
SELECT_MENU: {
/**
 * Select a category
 */
TITLE: () => LocalizedString
/**
 * {category} commands
 */
CATEGORY_DESCRIPTION: (arg: { category: string }) => LocalizedString
}
}
PING: {
/**
 * Pong!
 */
DESCRIPTION: () => LocalizedString
/**
 * Pong! **Message round-trip took** `{time}ms`**.**
 */
MESSAGE: (arg: { time: number }) => LocalizedString
}
SLOWMODE: {
/**
 * Set slowmode for a channel.
 */
DESCRIPTION: () => LocalizedString
/**
 * Slowmode set by /slowmode
 */
REASON: () => LocalizedString
EMBED: {
/**
 * Set Slowmode Result
 */
TITLE: () => LocalizedString
/**
 * Slowmode in provided channels was set to `{time}` for `{length}`.
 */
DESCRIPTION: (arg: { length: string, time: string }) => LocalizedString
/**
 * Set slowmode for {channels} channels
 */
TASK_SUCCESS_MULTIPLE: (arg: { channels: number }) => LocalizedString
/**
 * Set slowmode for <#{channel_id}>
 */
TASK_SUCCESS_SINGLE: (arg: { channel_id: string }) => LocalizedString
/**
 * Failed to set slowmode for {channels} channels
 */
TASK_FAILED_MULTIPLE: (arg: { channels: number }) => LocalizedString
/**
 * Failed to set slowmode for <#{channel_id}>
 */
TASK_FAILED_SINGLE: (arg: { channel_id: string }) => LocalizedString
}
}
WARN: {
/**
 * Warn a user.
 */
DESCRIPTION: () => LocalizedString
/**
 * No reason provided
 */
REASON: () => LocalizedString
EMBED: {
/**
 * Warn Result
 */
TITLE: () => LocalizedString
/**
 * **Warned {user} ||** {reason}.
 */
DESCRIPTION: (arg: { reason: string, user: string }) => LocalizedString
/**
 * Successfully created warn for user
 */
TASK_SUCCESS_CREATE: () => LocalizedString
/**
 * Failed to create warn for user
 */
TASK_FAILED_CREATE: () => LocalizedString
/**
 * Successfully sent DM to user
 */
TASK_SUCCESS_DM: () => LocalizedString
/**
 * Could not DM user (are their DMs closed?)
 */
TASK_FAILED_DM: () => LocalizedString
}
}
}
}

export type Formatters = {}
